version: 2.1

orbs:
  node: circleci/node@4.1.0
  artifactory: circleci/artifactory@1.0.0

executors:
  default:
    docker:
      - image: 'cimg/base:stable'

jobs:
  test:
    executor: default
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version

workflows:
  test:
    jobs:
      - test
