version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14.12.0
    working_directory: ~/repo

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: npm run build
  test:
    executor: default
    steps:
      - checkout
      - run: npm run test

workflows:
  version: 2.1
    build_and_test:
      jobs:
        - build
        - test
