version: 2.1

orbs:
  node: circleci/node@4.1.0
  artifactory: circleci/artifactory@1.0.0
  docker: circleci/docker@1.4.0

executors:
  default:
    docker:
      - image: 'circleci/node:14.12.0'

jobs:
  #Install_Nodejs:
  #  executor: default
  #  steps:
  #    - checkout
  #    - node/install:
  #        install-yarn: true
  #    - run: node --version

  build-scan:
    executor: default
    environment:
      ARTIFACTORY_API_KEY: AKCp8hyQE8Q3zdedsnYk3PNrxcam1yjGDriyaqe7syb12denR4JkrjBgMsKz78VQ1vj5KTuKN
      ARTIFACTORY_URL: https://mmjfrog.jfrog.io/artifactory
      ARTIFACTORY_USER: mmjfrog2020@gmail.com
      ARTIFACTORY_DOCKER_REGISTRY: docker-local
    steps:
      - checkout
      
      - run:
          name: Login npm
          command: |
            npm config set registry https://mmjfrog.jfrog.io/artifactory/api/npm/lib-snapshot/
            #npm config set @<SCOPE>:registry https://mmjfrog.jfrog.io/artifactory/api/npm/lib-snapshot/
            npm install npmrc
            npmrc work
            #npm login
            
      
      #- setup_remote_docker
      #- artifactory/install
      #- artifactory/configure:
      #    artifactory-key: ARTIFACTORY_API_KEY
      #    artifactory-url: ARTIFACTORY_URL
      #    artifactory-user: ARTIFACTORY_USER
      #- run: 
      #    name: Build Docker image
      #    command: |
      #      echo $CIRCLE_SHA1
      #      #docker build --help
      #      docker build -t $ARTIFACTORY_DOCKER_REGISTRY/demo-build:$CIRCLE_SHA1 .
      #- run:
      #    name: Test
      #    command: |
      #      docker ps
      #- run:
      #    name: jfrog push
      #    command: |
      #      ./jfrog rt u "/home/circleci/project/target/*.jar" java-work --build-name=test --build-number=$CIRCLE_BUILD_NUM --flat=false
      #      ./jfrog rt u "multi*/*.jar" <artifactory_repo_name>          --build-name=<name_you_give_to_build> --build-number=$CIRCLE_BUILD_NUM --flat=false
      #      ./jfrog rt dp $ARTIFACTORY_DOCKER_REGISTRY/demo-build:$CIRCLE_SHA1 circle-artifactory --build-name=demo-build --build-number=$CIRCLE_SHA1
      #- run: 
      #    name: Build Docker image
      #    command: |
      #      docker build -t $ARTIFACTORY_DOCKER_REGISTRY/demo-build:$CIRCLE_SHA1 .
      #- run:
      #    name: Login to Docker
      #    command: |
      #      docker login --username=$ARTIFACTORY_USER --password=$ARTIFACTORY_API_KEY $ARTIFACTORY_DOCKER_REGISTRY
      #- run: 
      #    name: JFrog Commands 
      #    command: |
      #      jfrog rt dp $ARTIFACTORY_DOCKER_REGISTRY/demo-build:$CIRCLE_SHA1 circle-artifactory --build-name=demo-build --build-number=$CIRCLE_SHA1
      #      jfrog rt bce demo-build $CIRCLE_SHA1
      #      jfrog rt bp demo-build $CIRCLE_SHA1
      #      jfrog rt bs demo-build $CIRCLE_SHA1

workflows:
  test:
    jobs:
      - build-scan
